apiVersion: apps/v1
kind: Deployment
metadata:
  name: hf_ocr
spec:
  selector:
    matchLabels:
      app: hf_ocr
  template:
    metadata:
      labels:
        app: hf_ocr
    spec:
      containers:
        - name: hf_ocr
          image: okinasylv/hf_ocr:{{ .Values.env.APP_VERSION }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          readinessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
                path: /health
                port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3